configuration: Release
init:
  - git config --global core.autocrlf true
before_build:
  - dotnet restore
# Will build dependencies in release (optimize and portable pdbs) mode:
build_script:
  - cmd: for /f %%a in ('dir /b test') do dotnet test -c %configuration% test/%%a/%%a.csproj
after_build:
# packing the current Release build of all projects under src/
  #- cmd: for /f %%a in ('dir /b src') do dotnet pack --no-build -c Debug src/%%a/%%a.csproj
  - ps: Get-ChildItem .\src\ |  ForEach-Object {if ($_.name.Contains("Redis")){dotnet pack -c $env:Configuration src/$_/$_.csproj} else {dotnet pack --no-build -c $env:Configuration src/$_/$_.csproj}}
# Will build in Coverage mode (full pdbs) and upload coverage to Codecov
on_success:
  - ps: .\coverage.ps1 -UploadCodecov
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
os: Visual Studio 2017
assembly_info:
  patch: true
  file: GlobalAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{branch} - $(APPVEYOR_REPO_COMMIT)'
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
artifacts:
- path: '**\*.nupkg'
  name: greentube-monitoring-nuget-packages
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
